#include "builtin_registry.h"

#include <unordered_map>
#include <unordered_set>

namespace ir
{

// ── Python builtins (guaranteed by CPython) ─────────────────────
static const std::unordered_set<std::string> &pyBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// Built-in functions — always available
			"abs",
			"all",
			"any",
			"ascii",
			"bin",
			"bool",
			"bytearray",
			"bytes",
			"callable",
			"chr",
			"classmethod",
			"compile",
			"complex",
			"delattr",
			"dict",
			"dir",
			"divmod",
			"enumerate",
			"eval",
			"exec",
			"filter",
			"float",
			"format",
			"frozenset",
			"getattr",
			"globals",
			"hasattr",
			"hash",
			"hex",
			"id",
			"input",
			"int",
			"isinstance",
			"issubclass",
			"iter",
			"len",
			"list",
			"locals",
			"map",
			"max",
			"memoryview",
			"min",
			"next",
			"object",
			"oct",
			"open",
			"ord",
			"pow",
			"print",
			"property",
			"range",
			"repr",
			"reversed",
			"round",
			"set",
			"setattr",
			"slice",
			"sorted",
			"staticmethod",
			"str",
			"sum",
			"super",
			"tuple",
			"type",
			"vars",
			"zip",
			"__import__",
			// Built-in exceptions (commonly raised/caught by name)
			"Exception",
			"ValueError",
			"TypeError",
			"KeyError",
			"IndexError",
			"AttributeError",
			"RuntimeError",
			"StopIteration",
			"NotImplementedError",
			"AssertionError",
			"ImportError",
			"ModuleNotFoundError",
			"FileNotFoundError",
			"OSError",
			"IOError",
			"ZeroDivisionError",
			"NameError",
			"UnboundLocalError",
			"SyntaxError",
			"IndentationError",
			"TabError",
			"SystemExit",
			"KeyboardInterrupt",
			"GeneratorExit",
			"BaseException",
			// Common built-in types/classes
			"True",
			"False",
			"None",
			"Ellipsis",
			"NotImplemented",
		};
	return *s;
}

static const std::unordered_set<std::string> &pyStdlib()
{
	static const std::unordered_set<
		std::string> *s = new std::unordered_set<std::string>{
		// Python standard library — most commonly used modules and their
		// top-level functions. These are project-external but well-known.
		// Loaded as: `import os` → os.path.join(...) references "join"
		// We only register the "short name" (method/function) here.
		// Full qualified names are resolved via the import map.
		"os",
		"sys",
		"re",
		"json",
		"math",
		"time",
		"datetime",
		"collections",
		"itertools",
		"functools",
		"pathlib",
		"shutil",
		"subprocess",
		"typing",
		"enum",
		"dataclasses",
		"abc",
		"copy",
		"random",
		"statistics",
		"hashlib",
		"base64",
		"uuid",
		"tempfile",
		"logging",
		"warnings",
		"traceback",
		"pickle",
		"io",
		"threading",
		"multiprocessing",
		"asyncio",
		"concurrent",
		"unittest",
		"pytest",
		"doctest",
		"csv",
		"configparser",
		"xml",
		"html",
		"textwrap",
		"argparse",
		"getopt",
		"platform",
		"socket",
		"http",
		"email",
		"urllib",
		"requests",
		"httpx",
	};
	return *s;
}

static const std::unordered_set<std::string> &pyThirdParty()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// High-frequency third-party library symbols
			// numpy
			"numpy",
			"np",
			"ndarray",
			"array",
			"zeros",
			"ones",
			"empty",
			"arange",
			"linspace",
			"reshape",
			"transpose",
			"concatenate",
			"stack",
			"split",
			"dot",
			"matmul",
			"sum",
			"mean",
			"std",
			"var",
			"min",
			"max",
			"argmin",
			"argmax",
			"sort",
			"unique",
			"where",
			"clip",
			"abs",
			"sqrt",
			"exp",
			"log",
			"sin",
			"cos",
			"linspace",
			"meshgrid",
			"random",
			"seed",
			"normal",
			"uniform",
			"randint",
			"randn",
			"rand",
			"histogram",
			"fft",
			"ifft",
			// pandas
			"pandas",
			"pd",
			"DataFrame",
			"Series",
			"read_csv",
			"read_excel",
			"read_json",
			"read_sql",
			"to_csv",
			"to_excel",
			"to_json",
			"to_sql",
			"merge",
			"join",
			"concat",
			"groupby",
			"pivot_table",
			"melt",
			"crosstab",
			"cut",
			"qcut",
			"get_dummies",
			"dropna",
			"fillna",
			"replace",
			"astype",
			"value_counts",
			"sort_values",
			"sort_index",
			"reset_index",
			"set_index",
			"loc",
			"iloc",
			"at",
			"iat",
			"apply",
			"applymap",
			"pipe",
			// matplotlib
			"matplotlib",
			"plt",
			"figure",
			"plot",
			"scatter",
			"bar",
			"hist",
			"pie",
			"imshow",
			"contour",
			"subplot",
			"subplots",
			"xlabel",
			"ylabel",
			"title",
			"legend",
			"colorbar",
			"clf",
			"cla",
			"close",
			"savefig",
			"show",
			"tight_layout",
			"grid",
			"axis",
			"xlim",
			"ylim",
			"xticks",
			"yticks",
			"text",
			"annotate",
			"arrow",
			"fill_between",
			"stackplot",
			"semilogx",
			"semilogy",
			// plotly
			"plotly",
			"go",
			"px",
			"Figure",
			"Scatter",
			"Bar",
			"Pie",
			"Histogram",
			"Box",
			"Violin",
			"Heatmap",
			"Contour",
			"Surface",
			"Mesh3d",
			"Scatter3d",
			"Scattergeo",
			"add_trace",
			"add_scatter",
			"add_bar",
			"add_histogram",
			"add_vline",
			"add_hline",
			"add_vrect",
			"add_hrect",
			"add_shape",
			"add_annotation",
			"add_layout_image",
			"update_layout",
			"update_traces",
			"update_xaxes",
			"update_yaxes",
			"show",
			"write_html",
			"write_image",
			"to_html",
			"to_json",
			"from_json",
			"make_subplots",
			// torch
			"torch",
			"tensor",
			"FloatTensor",
			"LongTensor",
			"zeros",
			"ones",
			"rand",
			"randn",
			"arange",
			"cat",
			"stack",
			"split",
			"chunk",
			"gather",
			"scatter",
			"index_select",
			"masked_select",
			"nonzero",
			"where",
			"clone",
			"detach",
			"requires_grad_",
			"backward",
			"grad",
			"no_grad",
			"enable_grad",
			"set_grad_enabled",
			"nn",
			"Module",
			"Linear",
			"Conv2d",
			"LSTM",
			"GRU",
			"Embedding",
			"Dropout",
			"BatchNorm1d",
			"BatchNorm2d",
			"LayerNorm",
			"ReLU",
			"Sigmoid",
			"Tanh",
			"Softmax",
			"LogSoftmax",
			"CrossEntropyLoss",
			"MSELoss",
			"L1Loss",
			"NLLLoss",
			"optim",
			"SGD",
			"Adam",
			"AdamW",
			"RMSprop",
			"lr_scheduler",
			"DataLoader",
			"Dataset",
			"TensorDataset",
			"random_split",
			"save",
			"load",
			"jit",
			"onnx",
			"utils",
			"functional",
			// tensorflow / keras
			"tensorflow",
			"tf",
			"keras",
			"Sequential",
			"Model",
			"Layer",
			"Dense",
			"Conv2D",
			"MaxPooling2D",
			"Flatten",
			"Dropout",
			"LSTM",
			"GRU",
			"Embedding",
			"BatchNormalization",
			"compile",
			"fit",
			"predict",
			"evaluate",
			"save",
			"load_model",
			// scikit-learn
			"sklearn",
			"train_test_split",
			"cross_val_score",
			"GridSearchCV",
			"RandomizedSearchCV",
			"Pipeline",
			"make_pipeline",
			"LinearRegression",
			"LogisticRegression",
			"SVM",
			"SVC",
			"RandomForestClassifier",
			"RandomForestRegressor",
			"GradientBoostingClassifier",
			"KMeans",
			"PCA",
			"TSNE",
			"StandardScaler",
			"MinMaxScaler",
			"LabelEncoder",
			"accuracy_score",
			"precision_score",
			"recall_score",
			"f1_score",
			"confusion_matrix",
			"classification_report",
			// FastAPI / Flask
			"FastAPI",
			"flask",
			"Flask",
			"app",
			"Route",
			"get",
			"post",
			"put",
			"delete",
			"patch",
			"Request",
			"Response",
			"JSONResponse",
			"Body",
			"Query",
			"Path",
			"Header",
			"Cookie",
			"Form",
			"File",
			"UploadFile",
			"Depends",
			"HTTPException",
			"APIRouter",
			// Pydantic
			"pydantic",
			"BaseModel",
			"Field",
			"validator",
			"root_validator",
			// SQLAlchemy
			"sqlalchemy",
			"Column",
			"Integer",
			"String",
			"Float",
			"Boolean",
			"DateTime",
			"ForeignKey",
			"Table",
			"create_engine",
			"sessionmaker",
			"scoped_session",
			"declarative_base",
			"relationship",
			"backref",
			// pytest
			"pytest",
			"fixture",
			"mark",
			"parametrize",
			"skip",
			"skipif",
			"raises",
			"approx",
			"config",
			"tmpdir",
			"tmp_path",
			"monkeypatch",
			// Other common
			"tqdm",
			"tqdm_notebook",
			"click",
			"rich",
			"progress",
			"loguru",
			"structlog",
			"sentry_sdk",
			"dataclass",
			"field",
			"asdict",
			"astuple",
			"decorator",
			"wraps",
			"lru_cache",
			"cached_property",
			"partial",
			"reduce",
			"singledispatch",
		};
	return *s;
}

// ── C builtins ──────────────────────────────────────────────────
static const std::unordered_set<std::string> &cBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// C standard library functions
			"printf",
			"sprintf",
			"snprintf",
			"fprintf",
			"scanf",
			"sscanf",
			"fscanf",
			"puts",
			"gets",
			"fputs",
			"fgets",
			"putchar",
			"getchar",
			"perror",
			"strerror",
			"malloc",
			"calloc",
			"realloc",
			"free",
			"aligned_alloc",
			"memcpy",
			"memmove",
			"memset",
			"memcmp",
			"memchr",
			"strlen",
			"strcpy",
			"strncpy",
			"strcat",
			"strncat",
			"strcmp",
			"strncmp",
			"strchr",
			"strrchr",
			"strstr",
			"strtok",
			"strdup",
			"strndup",
			"strtol",
			"strtoll",
			"strtoul",
			"strtoull",
			"strtof",
			"strtod",
			"strtold",
			"atoi",
			"atol",
			"atoll",
			"atof",
			"fopen",
			"fclose",
			"fread",
			"fwrite",
			"fseek",
			"ftell",
			"rewind",
			"fflush",
			"feof",
			"ferror",
			"clearerr",
			"remove",
			"rename",
			"tmpfile",
			"tmpnam",
			"qsort",
			"bsearch",
			"abs",
			"labs",
			"llabs",
			"div",
			"ldiv",
			"lldiv",
			"rand",
			"srand",
			"exit",
			"abort",
			"atexit",
			"quick_exit",
			"_Exit",
			"getenv",
			"system",
			"assert",
			"signal",
			"raise",
			"setjmp",
			"longjmp",
			"va_start",
			"va_end",
			"va_arg",
			"va_copy",
			"offsetof",
			"sizeof",
			// C99 math
			"sin",
			"cos",
			"tan",
			"asin",
			"acos",
			"atan",
			"atan2",
			"sinh",
			"cosh",
			"tanh",
			"asinh",
			"acosh",
			"atanh",
			"exp",
			"log",
			"log10",
			"log2",
			"log1p",
			"expm1",
			"pow",
			"sqrt",
			"cbrt",
			"hypot",
			"ceil",
			"floor",
			"round",
			"trunc",
			"fabs",
			"fmod",
			"fmin",
			"fmax",
			"fdim",
			"erf",
			"erfc",
			"tgamma",
			"lgamma",
			// Common POSIX / system calls
			"open",
			"close",
			"read",
			"write",
			"lseek",
			"stat",
			"fstat",
			"mmap",
			"munmap",
			"mprotect",
			"mlock",
			"munlock",
			"fork",
			"execvp",
			"execve",
			"wait",
			"waitpid",
			"waitid",
			"pipe",
			"dup",
			"dup2",
			"fcntl",
			"ioctl",
			"select",
			"poll",
			"epoll_create",
			"epoll_ctl",
			"epoll_wait",
			"getpid",
			"getppid",
			"getuid",
			"geteuid",
			"getgid",
			"getegid",
			"chdir",
			"getcwd",
			"mkdir",
			"rmdir",
			"unlink",
			"symlink",
			"readlink",
			"opendir",
			"readdir",
			"closedir",
			"scandir",
			"socket",
			"bind",
			"listen",
			"accept",
			"connect",
			"send",
			"recv",
			"sendto",
			"recvfrom",
			"setsockopt",
			"getsockopt",
			"htons",
			"htonl",
			"ntohs",
			"ntohl",
			"inet_pton",
			"inet_ntop",
			"getaddrinfo",
			"freeaddrinfo",
			"gethostbyname",
			// pthread
			"pthread_create",
			"pthread_join",
			"pthread_detach",
			"pthread_mutex_lock",
			"pthread_mutex_unlock",
			"pthread_mutex_init",
			"pthread_mutex_destroy",
			"pthread_cond_wait",
			"pthread_cond_signal",
			"pthread_cond_broadcast",
			"pthread_self",
			"pthread_exit",
			"pthread_cancel",
			// C11 threads
			"thrd_create",
			"thrd_join",
			"thrd_detach",
			"thrd_exit",
			"mtx_init",
			"mtx_lock",
			"mtx_unlock",
			"mtx_destroy",
			"cnd_wait",
			"cnd_signal",
			"cnd_broadcast",
			// Common type names (used as constructor calls in C++)
			"int",
			"long",
			"float",
			"double",
			"char",
			"short",
			"unsigned",
			"void",
			"size_t",
			"ssize_t",
			"int8_t",
			"int16_t",
			"int32_t",
			"int64_t",
			"uint8_t",
			"uint16_t",
			"uint32_t",
			"uint64_t",
			"NULL",
			"nullptr",
			"true",
			"false",
			"bool",
		};
	return *s;
}

// ── C++ builtins ────────────────────────────────────────────────
static const std::unordered_set<std::string> &cppBuiltins()
{
	// C++ includes all C builtins, plus STL
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// STL containers
			"vector",
			"map",
			"unordered_map",
			"set",
			"unordered_set",
			"list",
			"deque",
			"forward_list",
			"array",
			"span",
			"string",
			"string_view",
			"wstring",
			"pair",
			"tuple",
			"optional",
			"variant",
			"any",
			"shared_ptr",
			"unique_ptr",
			"weak_ptr",
			"function",
			"bind",
			"ref",
			"cref",
			// STL algorithms
			"sort",
			"stable_sort",
			"partial_sort",
			"nth_element",
			"find",
			"find_if",
			"find_if_not",
			"binary_search",
			"lower_bound",
			"upper_bound",
			"equal_range",
			"count",
			"count_if",
			"for_each",
			"transform",
			"copy",
			"copy_if",
			"move",
			"fill",
			"generate",
			"replace",
			"replace_if",
			"remove",
			"remove_if",
			"unique",
			"reverse",
			"rotate",
			"shuffle",
			"random_shuffle",
			"min",
			"max",
			"minmax",
			"clamp",
			"accumulate",
			"inner_product",
			"adjacent_difference",
			"partial_sum",
			// STL I/O
			"cin",
			"cout",
			"cerr",
			"clog",
			"endl",
			"flush",
			// STL utilities
			"make_shared",
			"make_unique",
			"make_pair",
			"make_tuple",
			"make_optional",
			"make_variant",
			"make_any",
			"static_cast",
			"dynamic_cast",
			"const_cast",
			"reinterpret_cast",
			// C++17/20/23 filesystem
			"filesystem",
			"path",
			"directory_iterator",
			"recursive_directory_iterator",
			"exists",
			"is_directory",
			"is_regular_file",
			"file_size",
			"create_directory",
			"remove",
			"rename",
			"copy",
			"current_path",
			"temp_directory_path",
			// C++20/23 ranges
			"ranges",
			"views",
			"begin",
			"end",
			"size",
			"empty",
			"data",
			"front",
			"back",
			"at",
			"cbegin",
			"cend",
			// Threading
			"thread",
			"jthread",
			"mutex",
			"lock_guard",
			"unique_lock",
			"shared_lock",
			"scoped_lock",
			"condition_variable",
			"future",
			"promise",
			"async",
			"packaged_task",
			"atomic",
			"memory_order",
			// Common macros expanded as identifiers
			"assert",
			"static_assert",
			"sizeof",
			"alignof",
			"typeid",
			"noexcept",
			"override",
			"final",
			"default",
			"delete",
			"constexpr",
			"consteval",
			"constinit",
			"co_await",
			"co_yield",
			"co_return",
		};
	return *s;
}

// ── Rust builtins ───────────────────────────────────────────────
static const std::unordered_set<std::string> &rustBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// Core language primitives
			"Some",
			"None",
			"Ok",
			"Err",
			"Result",
			"Option",
			"Box",
			"Vec",
			"String",
			"str",
			"HashMap",
			"HashSet",
			"BTreeMap",
			"BTreeSet",
			"LinkedList",
			"VecDeque",
			"Rc",
			"Arc",
			"Cell",
			"RefCell",
			"Mutex",
			"RwLock",
			// Macros (most commonly used)
			"println",
			"print",
			"eprintln",
			"eprint",
			"format",
			"vec",
			"vec_deque",
			"btreemap",
			"btreeset",
			"hashmap",
			"format_args",
			"concat",
			"stringify",
			"include_str",
			"include_bytes",
			"include!",
			"env",
			"option_env",
			"cfg",
			"cfg_attr",
			"column",
			"file",
			"line",
			"module_path",
			"todo",
			"unimplemented",
			"unreachable",
			"panic",
			"assert",
			"assert_eq",
			"assert_ne",
			"debug_assert",
			"debug_assert_eq",
			"debug_assert_ne",
			"matches",
			"dbg",
			"write",
			"writeln",
			// Core traits
			"Clone",
			"Copy",
			"Debug",
			"Display",
			"Default",
			"PartialEq",
			"Eq",
			"PartialOrd",
			"Ord",
			"Hash",
			"Into",
			"From",
			"TryInto",
			"TryFrom",
			"IntoIterator",
			"FromIterator",
			"AsRef",
			"AsMut",
			"Deref",
			"DerefMut",
			"Drop",
			"Send",
			"Sync",
			"Unpin",
			"Sized",
			// std library
			"std",
			"core",
			"alloc",
			"proc_macro",
			// Common third-party crates
			"serde",
			"Serialize",
			"Deserialize",
			"serde_json",
			"tokio",
			"async_std",
			"futures",
			"rayon",
			"reqwest",
			"hyper",
			"actix",
			"axum",
			"warp",
			"rocket",
			"clap",
			"structopt",
			"anyhow",
			"thiserror",
			"log",
			"env_logger",
			"tracing",
			"tracing_subscriber",
			"chrono",
			"uuid",
			"rand",
			"regex",
			"lazy_static",
			"once_cell",
			"parking_lot",
			"crossbeam",
			"diesel",
			"sqlx",
			"rusqlite",
			"mongodb",
			"tonic",
			"prost",
			"protobuf",
			"tempfile",
			"walkdir",
			"glob",
			"ignore",
		};
	return *s;
}

// ── Go builtins ─────────────────────────────────────────────────
static const std::unordered_set<std::string> &goBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// Built-in functions
			"append",
			"cap",
			"close",
			"complex",
			"copy",
			"delete",
			"imag",
			"len",
			"make",
			"new",
			"panic",
			"print",
			"println",
			"real",
			"recover",
			// Built-in types
			"bool",
			"byte",
			"complex64",
			"complex128",
			"error",
			"float32",
			"float64",
			"int",
			"int8",
			"int16",
			"int32",
			"int64",
			"rune",
			"string",
			"uint",
			"uint8",
			"uint16",
			"uint32",
			"uint64",
			"uintptr",
			"nil",
			"true",
			"false",
			"iota",
			// Standard library: common packages
			"fmt",
			"io",
			"os",
			"net",
			"http",
			"json",
			"time",
			"strings",
			"strconv",
			"bytes",
			"bufio",
			"sort",
			"math",
			"rand",
			"crypto",
			"encoding",
			"compress",
			"sync",
			"atomic",
			"context",
			"reflect",
			"regexp",
			"log",
			"flag",
			"path",
			"filepath",
			"ioutil",
			"template",
			"html",
			"testing",
			"database/sql",
			// Common third-party
			"gin",
			"echo",
			"fiber",
			"chi",
			"gorilla",
			"mux",
			"gorm",
			"sqlx",
			"kafka",
			"redis",
			"mongodb",
			"protobuf",
			"grpc",
			"cobra",
			"viper",
			"zap",
			"prometheus",
			"otel",
			"opentracing",
			"jaeger",
		};
	return *s;
}

// ── Java builtins ───────────────────────────────────────────────
static const std::unordered_set<std::string> &javaBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// java.lang — always imported
			"Object",
			"String",
			"Integer",
			"Long",
			"Double",
			"Float",
			"Boolean",
			"Character",
			"Short",
			"Byte",
			"Void",
			"Number",
			"Math",
			"System",
			"Thread",
			"Runnable",
			"Class",
			"Throwable",
			"Exception",
			"RuntimeException",
			"Error",
			"NullPointerException",
			"IllegalArgumentException",
			"IndexOutOfBoundsException",
			"ArrayIndexOutOfBoundsException",
			"StringBuilder",
			"StringBuffer",
			"Comparable",
			"Cloneable",
			"Enum",
			"AutoCloseable",
			"Iterable",
			"Appendable",
			"Runtime",
			"Process",
			"ProcessBuilder",
			"SecurityManager",
			// Common collections
			"ArrayList",
			"LinkedList",
			"HashMap",
			"HashSet",
			"LinkedHashMap",
			"TreeMap",
			"TreeSet",
			"PriorityQueue",
			"ArrayDeque",
			"Collections",
			"Arrays",
			"Comparator",
			"Iterator",
			"ListIterator",
			"List",
			"Set",
			"Map",
			"Queue",
			"Deque",
			"Collection",
			// I/O
			"File",
			"Path",
			"Paths",
			"Files",
			"InputStream",
			"OutputStream",
			"Reader",
			"Writer",
			"BufferedReader",
			"BufferedWriter",
			"FileReader",
			"FileWriter",
			"PrintWriter",
			"Scanner",
			// Common frameworks
			"spring",
			"SpringBoot",
			"Autowired",
			"Service",
			"Component",
			"Repository",
			"Controller",
			"RestController",
			"RequestMapping",
			"GetMapping",
			"PostMapping",
			"PutMapping",
			"DeleteMapping",
			"PathVariable",
			"RequestParam",
			"RequestBody",
			"ResponseEntity",
			"jpa",
			"JpaRepository",
			"CrudRepository",
			"Entity",
			"Table",
			"Column",
			"Id",
			"GeneratedValue",
			"OneToMany",
			"ManyToOne",
			"lombok",
			"Data",
			"Getter",
			"Setter",
			"NoArgsConstructor",
			"AllArgsConstructor",
			"Builder",
			"Slf4j",
			"Log4j",
			"jackson",
			"JsonIgnore",
			"JsonProperty",
			"JsonFormat",
			"junit",
			"Test",
			"Before",
			"After",
			"BeforeEach",
			"AfterEach",
		};
	return *s;
}

// ── JavaScript / TypeScript builtins ────────────────────────────
static const std::unordered_set<std::string> &jsBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			// Global objects
			"Object",
			"Array",
			"String",
			"Number",
			"Boolean",
			"Symbol",
			"Function",
			"Date",
			"RegExp",
			"Error",
			"TypeError",
			"RangeError",
			"ReferenceError",
			"SyntaxError",
			"EvalError",
			"Promise",
			"Proxy",
			"Reflect",
			"Map",
			"Set",
			"WeakMap",
			"WeakSet",
			"JSON",
			"Math",
			"Intl",
			"Buffer",
			"console",
			"process",
			"global",
			"globalThis",
			// Global functions
			"parseInt",
			"parseFloat",
			"isNaN",
			"isFinite",
			"decodeURI",
			"decodeURIComponent",
			"encodeURI",
			"encodeURIComponent",
			"eval",
			"uneval",
			"escape",
			"unescape",
			// Array methods
			"map",
			"filter",
			"reduce",
			"reduceRight",
			"forEach",
			"find",
			"findIndex",
			"some",
			"every",
			"includes",
			"indexOf",
			"lastIndexOf",
			"push",
			"pop",
			"shift",
			"unshift",
			"splice",
			"slice",
			"concat",
			"join",
			"reverse",
			"sort",
			"flat",
			"flatMap",
			"from",
			"of",
			"isArray",
			"fill",
			"copyWithin",
			"entries",
			"keys",
			"values",
			// Object methods
			"keys",
			"values",
			"entries",
			"assign",
			"create",
			"defineProperty",
			"defineProperties",
			"getOwnPropertyDescriptor",
			"getOwnPropertyNames",
			"getPrototypeOf",
			"setPrototypeOf",
			"freeze",
			"seal",
			"preventExtensions",
			"isFrozen",
			"isSealed",
			"isExtensible",
			"hasOwnProperty",
			// String methods
			"charAt",
			"charCodeAt",
			"concat",
			"includes",
			"indexOf",
			"lastIndexOf",
			"match",
			"matchAll",
			"replace",
			"replaceAll",
			"search",
			"slice",
			"split",
			"substring",
			"substr",
			"toLowerCase",
			"toUpperCase",
			"trim",
			"trimStart",
			"trimEnd",
			"padStart",
			"padEnd",
			"repeat",
			"startsWith",
			"endsWith",
			"localeCompare",
			"normalize",
			"raw",
			"fromCharCode",
			"fromCodePoint",
			// Promise
			"then",
			"catch",
			"finally",
			"resolve",
			"reject",
			"all",
			"allSettled",
			"race",
			"any",
			"withResolvers",
			// Common Node.js
			"require",
			"module",
			"exports",
			"__dirname",
			"__filename",
			"setTimeout",
			"setInterval",
			"setImmediate",
			"clearTimeout",
			"clearInterval",
			"clearImmediate",
			"queueMicrotask",
			"Buffer",
			"fs",
			"path",
			"os",
			"util",
			"events",
			"stream",
			"http",
			"https",
			"net",
			"crypto",
			"url",
			"querystring",
			"child_process",
			"cluster",
			"worker_threads",
			// Common Web APIs
			"document",
			"window",
			"navigator",
			"location",
			"history",
			"localStorage",
			"sessionStorage",
			"fetch",
			"WebSocket",
			"setTimeout",
			"setInterval",
			"requestAnimationFrame",
			"addEventListener",
			"removeEventListener",
			"dispatchEvent",
			"querySelector",
			"querySelectorAll",
			"getElementById",
			"createElement",
			"appendChild",
			"removeChild",
			// Common TS/JS frameworks
			"react",
			"React",
			"useState",
			"useEffect",
			"useContext",
			"useReducer",
			"useCallback",
			"useMemo",
			"useRef",
			"useImperativeHandle",
			"useLayoutEffect",
			"useDebugValue",
			"useTransition",
			"useDeferredValue",
			"createContext",
			"createRef",
			"forwardRef",
			"memo",
			"Fragment",
			"Component",
			"PureComponent",
			"createElement",
			"cloneElement",
			"isValidElement",
			"Children",
			"StrictMode",
			"Suspense",
			"lazy",
			"startTransition",
			"useId",
			"useSyncExternalStore",
			"vue",
			"Vue",
			"ref",
			"computed",
			"watch",
			"watchEffect",
			"onMounted",
			"onUnmounted",
			"onUpdated",
			"nextTick",
			"defineComponent",
			"defineProps",
			"defineEmits",
			"defineExpose",
			"angular",
			"NgModule",
			"Component",
			"Injectable",
			"Inject",
			"Input",
			"Output",
			"EventEmitter",
			"HostListener",
			"Directive",
			"Pipe",
			"Service",
			"Observable",
			"Subject",
			"BehaviorSubject",
			"express",
			"Router",
			"next",
			"Request",
			"Response",
			"lodash",
			"_",
			"axios",
			"moment",
			"dayjs",
			"jest",
			"describe",
			"it",
			"expect",
			"beforeEach",
			"afterEach",
			"beforeAll",
			"afterAll",
			"test",
			"mock",
			"spyOn",
		};
	return *s;
}

// ── Swift builtins ──────────────────────────────────────────────
static const std::unordered_set<std::string> &swiftBuiltins()
{
	static const std::unordered_set<std::string> *s =
		new std::unordered_set<std::string>{
			"print",
			"debugPrint",
			"dump",
			"fatalError",
			"precondition",
			"preconditionFailure",
			"assert",
			"assertionFailure",
			"abs",
			"min",
			"max",
			"stride",
			"stride",
			"sequence",
			"zip",
			"swap",
			"type",
			"unsafeBitCast",
			"unsafeDowncast",
			"Array",
			"Dictionary",
			"Set",
			"String",
			"Substring",
			"Optional",
			"Result",
			"Bool",
			"Int",
			"UInt",
			"Float",
			"Double",
			"CGFloat",
			"Character",
			"Data",
			"Date",
			"UUID",
			"URL",
			"Error",
			"Codable",
			"Encodable",
			"Decodable",
			"Equatable",
			"Hashable",
			"Comparable",
			"Identifiable",
			"CustomStringConvertible",
			"CustomDebugStringConvertible",
			"UIView",
			"UIViewController",
			"UITableView",
			"UICollectionView",
			"UIStackView",
			"UILabel",
			"UIButton",
			"UIImageView",
			"UITextField",
			"NSObject",
			"NSArray",
			"NSDictionary",
			"NSString",
			"UserDefaults",
			"NotificationCenter",
			"FileManager",
			"Bundle",
			"DispatchQueue",
			"DispatchGroup",
			"DispatchWorkItem",
			"OperationQueue",
			"Timer",
			"RunLoop",
			"Thread",
			"Lock",
			"JSONEncoder",
			"JSONDecoder",
			"PropertyListEncoder",
			"PropertyListDecoder",
			"URLSession",
			"URLRequest",
			"URLResponse",
			"HTTPURLResponse",
			"DataTask",
			"UploadTask",
			"DownloadTask",
			// SwiftUI
			"View",
			"Text",
			"Image",
			"Button",
			"TextField",
			"Toggle",
			"Slider",
			"Stepper",
			"Picker",
			"DatePicker",
			"ColorPicker",
			"List",
			"ScrollView",
			"VStack",
			"HStack",
			"ZStack",
			"Spacer",
			"Divider",
			"Group",
			"Section",
			"Form",
			"NavigationView",
			"NavigationLink",
			"TabView",
			"Sheet",
			"Alert",
			"Popover",
			"State",
			"Binding",
			"ObservedObject",
			"StateObject",
			"EnvironmentObject",
			"Environment",
			"Published",
			"ObservableObject",
			"@main",
			"@UIApplicationMain",
			"@main",
		};
	return *s;
}

// ── Registry dispatch ───────────────────────────────────────────
// Map language → symbol set
using SymbolTable = std::unordered_set<std::string>;
using RegistryMap =
	std::unordered_map<std::string, std::vector<const SymbolTable *>>;

static const RegistryMap &registry()
{
	static const RegistryMap *m = new RegistryMap{
		{ "python", { &pyBuiltins(), &pyStdlib(), &pyThirdParty() } },
		{ "c", { &cBuiltins() } },
		{ "cpp", { &cBuiltins(), &cppBuiltins() } },
		{ "rust", { &rustBuiltins() } },
		{ "go", { &goBuiltins() } },
		{ "java", { &javaBuiltins() } },
		{ "javascript", { &jsBuiltins() } },
		{ "typescript", { &jsBuiltins() } },
		{ "js", { &jsBuiltins() } },
		{ "ts", { &jsBuiltins() } },
		{ "swift", { &swiftBuiltins() } },
	};
	return *m;
}

std::string BuiltinRegistry::resolve(const std::string &language,
				     const std::string &name)
{
	if (name.empty())
		return "unresolved";

	auto it = registry().find(language);
	if (it == registry().end()) {
		// Unknown language — fall back to checking all tables
		for (const auto &[lang, tables] : registry()) {
			(void)lang;
			for (const auto *table : tables) {
				if (table->count(name))
					return "external";
			}
		}
		return "unresolved";
	}

	for (const auto *table : it->second) {
		if (table->count(name))
			return "external";
	}

	return "unresolved";
}

bool BuiltinRegistry::isKnownExternal(const std::string &name)
{
	for (const auto &[lang, tables] : registry()) {
		(void)lang;
		for (const auto *table : tables) {
			if (table->count(name))
				return true;
		}
	}
	return false;
}

const std::unordered_set<std::string> &
BuiltinRegistry::externalSymbols(const std::string &language)
{
	static const std::unordered_set<std::string> empty;
	auto it = registry().find(language);
	if (it == registry().end())
		return empty;
	// Return the union of all tables for this language.
	// We use a static cache to avoid recomputing on each call.
	static std::unordered_map<std::string, std::unordered_set<std::string>>
		cache;
	auto cache_it = cache.find(language);
	if (cache_it != cache.end())
		return cache_it->second;
	std::unordered_set<std::string> merged;
	for (const auto *table : it->second) {
		for (const auto &sym : *table)
			merged.insert(sym);
	}
	auto result = cache.emplace(language, std::move(merged));
	return result.first->second;
}

} // namespace ir